name: Deploy Gatus

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
concurrency:
  group: terraform-ephemeral
  cancel-in-progress: false
jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::313196411727:role/git-role
          aws-region: eu-west-2

      - name: Amazon ECR "Login" Action for GitHub Actions
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Set image reference
        run: echo "IMAGE_REF=${{ steps.login-ecr.outputs.registry }}/my-gatus:${{ github.sha }}" >> "$GITHUB_ENV"

      - name: Check if image exists
        id: check-image
        run: |
         if aws ecr describe-images --repository-name my-gatus --image-ids imageTag=${{ github.sha }} 2>/dev/null; then
         echo "exists=true" >> $GITHUB_OUTPUT
         else
         echo "exists=false" >> $GITHUB_OUTPUT
         fi

      - name: Build image
        if: steps.check-image.outputs.exists == 'false'
        run: docker build -t "$IMAGE_REF" .


      - name: Trivy scan
        if: steps.check-image.outputs.exists == 'false'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REF }}
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Push to ECR
        if: steps.check-image.outputs.exists == 'false'
        run: docker push "$IMAGE_REF"

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infrastrucure/


  terraform-apply:
    runs-on: ubuntu-latest
    needs: [build-scan-push, checkov]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::313196411727:role/git-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infrastructure/ephemeral
        run: terraform init

      - name: Terraform Apply
        working-directory: infrastructure/ephemeral
        run: |
          terraform apply -auto-approve -var="image_tag=${{ github.sha }}"
